version: '3.8'

services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sqps-doc-retype
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: unless-stopped
